# Alacritty Configuration File (示例)

[window]
  # 窗口尺寸（以列和行计算）
  dimensions = { columns = 80, lines = 24 }

  # 窗口填充（以像素为单位）
  padding = { x = 10, y = 10 }

  # 窗口装饰
  decorations = "full"

[font]
  normal = { family = "Agave Nerd Font", style = "Regular" }
  bold = { family = "Agave Nerd Font", style = "Bold" }
  italic = { family = "Agave Nerd Font", style = "Italic" }
  size = 11.0

[colors]
  primary = { background = "0x1e1e1e", foreground = "0xc5c8c6" }

  [colors.normal]
    black = "0x1c1c1c"
    red = "0xc82829"
    green = "0xb9ca4a"
    yellow = "0xeab700"
    blue = "0x7aa6da"
    magenta = "0xc397d8"
    cyan = "0x70c3c1"
    white = "0xffffff"

  [colors.bright]
    black = "0x666666"
    red = "0xf92672"
    green = "0xa6e22e"
    yellow = "0xe6db74"
    blue = "0x66d9ef"
    magenta = "0xae81ff"
    cyan = "0xa1efe4"
    white = "0xffffff"

# [terminal.shell]
#  program = "/usr/bin/zsh"  # 或者 "/bin/zsh"
#  args = ["--login"]
