#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


#lemonpanel &
#~/.config/polybar/hack/launch.sh &
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a zenity state=floating
# bspc rule -a Copyq state=floating
bspc rule -a Emacs state=tiled

hdmi_output=$(xrandr -q | grep -Eo "HDMI-1-[0-3] connected" | awk '{print $1}')

if [ -n "$hdmi_output" ]; then
    xrandr --output "$hdmi_output" --auto --primary --output eDP-1 --auto --right-of "$hdmi_output"
    bspc monitor "$hdmi_output" -d I II III IV V
fi


bspc monitor eDP-1 -d VI VII VIII IX X

bspc desktop -f '^1'
feh --bg-fill -randomize $HOME/MyConf/wallpapers/*
picom &
bash ~/.config/polybar/launch.sh --hack &

# cd $HOME/.doom.d
# git add .
# git commit --amend
# cd $HOME/MyConf
# git add .
# git commit --amend
# cd $HOME/scripts
# git add .
# git commit --amend

mpd &
#emacs --daemon &
syncthing &
# copyq &
# keyd-application-mapper -d

ibus-daemon -drx &
