#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1-0 -d I II III IV V

bspc monitor eDP-1 -d VI VII VIII IX X

#lemonpanel &
#bash ~/.config/polybar/launch.sh --hack &
~/.config/polybar/hack/launch.sh &
mpd &
emacs --daemon &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

if xrandr -q | grep "HDMI-1-0 connected"; then
    xrandr --output HDMI-1-0 --auto --primary --output eDP-1 --auto --right-of HDMI-1-0
    #alacritty &
fi

feh --bg-fill $HOME/Downloads/blue-sky/wallpapers/blue3.png

cd $HOME/.doom.d
git add .
git commit -m "update"
git pull
cd $HOME/blogs
git add .
git commit -m "update"
git pull
cd $HOME/.config/ibus/rime
git add .
git commit -m "update"
git pull
