[project]
name = "py-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepseek>=1.0.0",
    "markitdown>=0.0.1a3",
    "neovim>=0.3.1",
    "pip>=25.0",
    "pywubi>=0.0.2",
    "virtualenv>=20.29.1",
    "yt-dlp>=2025.1.26",
]
