#!/usr/bin/env bash

while [[ $# -gt 0 ]]; do
    case "$1" in
        --class) CLASS="$2"; shift 2 ;;
        --name) NAME="$2"; shift 2 ;;
        *) shift ;;
    esac
done

winid=$(xdotool getactivewindow)

window_property_matches() {
    prop_value=$(xprop -id "$winid" "$1" 2>/dev/null)
    [[ $? -ne 0 ]] && exit 1
    echo "$prop_value" | grep -q "$2"
}

if [[ -n "$winid" ]]; then
    if [[ -n "$CLASS" ]]; then
        window_property_matches "WM_CLASS" "$CLASS" || exit 1
    fi
    if [[ -n "$NAME" ]]; then
        window_property_matches "WM_NAME" "$NAME" || exit 1
    fi
fi

exit 0
